name: run-tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: PHP 8.1 Unit tests & static analyzer

    steps:
      -   name: Checkout code
          uses: actions/checkout@v2

      -   name: Setup PHP
          uses: shivammathur/setup-php@v2
          with:
            php-version: 8.1
            # extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
            coverage: none
      -   name: Install dependencies
          run: |
            composer install
      -   name: Execute tests
          run: vendor/bin/phpunit
      -   name: Execute Static analyzer
          run: vendor/bin/phpstan analyse src --level=9
